- name: install epel
  yum:
      name: epel-release
      state: present
  tags: [nginx]

- name: install nginx
  yum:
      name: nginx
      state: present
  tags: [nginx]

- name: enable nginx
  service:
      name: nginx
      state: started
  tags: [nginx, status]

- name: copy nginx configuration file
  template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: u=rw,g=r,o=r
  notify: restart nginx
  tags: [nginx, config]
